### ISSUE TITLE
[Feature Request] Add 'Off Day' badge 

### ISSUE THREAD

**Issue by hessam-kk** [itismoradi-zz/hengam#1]
for those days which are holiday or off, add the badge 'Off' like this:
![image](https://user-images.githubusercontent.com/24957423/157240685-4a95896a-a549-406a-9491-774d2c3d1a5b.png)

**Comment by itismoradi-zz** [comment]
Holidays in the **Hijri lunar calendar** go back a little each year,
and on the other hand, this calendar depends on observing the moon in the sky.
For example, Eid al-Fitr may be one day behind or ahead.

If we do not consider the lunar calendar holidays;
In total, there are less than 15 holidays in the **Solar Hijri calendar** that we are trying to add.

thank you.

**Comment by itismoradi-zz** [comment]
added off-day badge.
95b5c3f6ff50088131b3504976e497779fa21bc8
